### PR TITLE
Replace hpc option by show_progress_bar/hide_progress_bar

### LINKED ISSUE #87: [JOSS Review] Performance and HPC
Dear authors,

Since HPC is pointed out in the paper (by mentioning it as an advantage of the current implementation and leveraging FEniCS), I think it should be elaborated a bit in the documentation. 

I couldn’t find anything regarding the parallel execution in the documentation. Are you relying on the user knowledge of FEniCS for this? If so, then the submission is useful for the FEniCS community only, limiting its potential to be used by broader users (I mentioned this as a problem for the installation documentation as well). I suggest that you explain how to run the code in parallel in the documentation. Also, what does the `hpc` argument do? It seems that it just turns off the progress bar, yes? 

Furthermore, in my tests using 6 CPU cores (done using the demo example), the code runs slower when I call it with MPI. I guess that it may be related to the problem size, but anyway, it can be nice if you add another demo (maybe with a bigger problem size) for demonstrating the parallel execution and its benefits. 

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/4753

### PR DESCRIPTION
**Pull request by cdaversin**
Fixes #87

## Proposed Changes
  ~~Remove hpc option - replaced by checking size of the global communicator to trun off progress bar if needed~~
   Remove hpc option - replaced by `--show_progress_bar` / `--hide_progress_bar`, to be more explicit

### CODE REVIEW

**Comment by finsberg** [comment]
I belive this flag was used primarily when running on the supercomputer (SAGA). The progressbar didn't show up nicely in the output files and then we added this flag to turn off the progressbar. Perhaps we can just rename the flag to `show-progressbar / no-show-progressbar` (see https://click.palletsprojects.com/en/8.1.x/options/#boolean-flags) ?

**Comment by cdaversin** [comment]
Yes, I remember that. But isn't it enough to check the size of the communicator, and if it is > 1 (running in parallel), then we turn off the progress bar ? And yes, using `show-progressbar` is also an option

**Comment by finsberg** [comment]
> Yes, I remember that. But isn't it enough to check the size of the communicator, and if it is > 1 (running in parallel), then we turn off the progress bar ? And yes, using `show-progressbar` is also a possibility (and better than `hpc` for sure)

@IlsevanHerck has to answer this one

**Comment by cdaversin** [comment]
Allright, then I will change this into a `show-progressbar` option and update this PR :)

**Comment by cdaversin** [comment]
Now we can use `--show_progress_bar` or `--hide_progress_bar`

**Comment by finsberg** [comment]
@cdaversin Looks good to me! Please merge it :)

**Review by finsberg — APPROVED** [review]

**Pull request merged**
